#!/usr/bin/env bash
# display information about subdomains
if [ "$#" -eq 2 ]; then
    dig www.$1 | grep -A1 'ANSWER SECTION:' | awk '{print "The subdomain " $1 " is a " $4 " record and points to " $5}'
    dig lb-01.$1 | grep -A1 'ANSWER SECTION:' | awk '{print "The subdomain lb-01 is a " $4 " record and points to " $5}'
    dig web-01.$1 | grep -A1 'ANSWER SECTION:' | awk '{print "The subdomain web-01 is a " $4 " record and points to " $5}'
    dig web-02.$1 | grep -A1 'ANSWER SECTION:' | awk '{print "The subdomain web-02 is a " $4 " record and points to " $5}'
    fi
if [ "$#" -eq 3 ]; then
    dig $2 | grep -A1 'ANSWER SECTION:' | awk '{print "The subdomain " $2 " is a " $4 " record and points to " $5}'
fi